version: '3'
services:
  db:
    image: mysql:latest
    restart: always
    volumes:
      - db_data1:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password321
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: password321

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    volumes:
      - wp_data:/var/www/html
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: password321
      WORDPRESS_DB_NAME: wordpress
volumes:
  db_data1: {}
  wp_data: {}

